version: "3.1"

services:
  # PostgreSQL Database
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cost-share
    networks:
      - postgres-network

  # Admin tool (replace phpMyAdmin with pgAdmin for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    networks:
      - postgres-network

networks:
  postgres-network:

volumes:
  db_data:
